"""add plan feature subscription tenant entitlement schema

Revision ID: 27ff755cb588
Revises: 9ca181e63f34
Create Date: 2026-08-28 20:09:59.955857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27ff755cb588'
down_revision: Union[str, Sequence[str], None] = '9ca181e63f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature_type', sa.Enum('core', 'addon', name='featuretype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='featurestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_code'), 'features', ['code'], unique=True)
    op.create_index(op.f('ix_features_module'), 'features', ['module'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('setup_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_amc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='planstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.create_table('plan_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'feature_id', name='uq_plan_feature')
    )
    op.create_index(op.f('ix_plan_features_feature_id'), 'plan_features', ['feature_id'], unique=False)
    op.create_index(op.f('ix_plan_features_plan_id'), 'plan_features', ['plan_id'], unique=False)
    op.create_table('plan_limits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('limit_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'limit_code', name='uq_plan_limit_code')
    )
    op.create_index(op.f('ix_plan_limits_limit_code'), 'plan_limits', ['limit_code'], unique=False)
    op.create_index(op.f('ix_plan_limits_plan_id'), 'plan_limits', ['plan_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_plan_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', name='tenantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_tenant_code'), 'tenants', ['tenant_code'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expiring', 'expired', 'suspended', 'grace_period', name='subscriptionstatus'), nullable=False),
    sa.Column('setup_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_amc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('tenant_feature_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_feature_overrides_feature_id'), 'tenant_feature_overrides', ['feature_id'], unique=False)
    op.create_index(op.f('ix_tenant_feature_overrides_tenant_id'), 'tenant_feature_overrides', ['tenant_id'], unique=False)
    op.create_table('tenant_limit_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('limit_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('override_value', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_limit_overrides_limit_code'), 'tenant_limit_overrides', ['limit_code'], unique=False)
    op.create_index(op.f('ix_tenant_limit_overrides_tenant_id'), 'tenant_limit_overrides', ['tenant_id'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('metric_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'metric_code', name='uq_tenant_metric')
    )
    op.create_index(op.f('ix_usage_counters_metric_code'), 'usage_counters', ['metric_code'], unique=False)
    op.create_index(op.f('ix_usage_counters_tenant_id'), 'usage_counters', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_counters_tenant_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_metric_code'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_tenant_limit_overrides_tenant_id'), table_name='tenant_limit_overrides')
    op.drop_index(op.f('ix_tenant_limit_overrides_limit_code'), table_name='tenant_limit_overrides')
    op.drop_table('tenant_limit_overrides')
    op.drop_index(op.f('ix_tenant_feature_overrides_tenant_id'), table_name='tenant_feature_overrides')
    op.drop_index(op.f('ix_tenant_feature_overrides_feature_id'), table_name='tenant_feature_overrides')
    op.drop_table('tenant_feature_overrides')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_tenants_tenant_code'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_plan_limits_plan_id'), table_name='plan_limits')
    op.drop_index(op.f('ix_plan_limits_limit_code'), table_name='plan_limits')
    op.drop_table('plan_limits')
    op.drop_index(op.f('ix_plan_features_plan_id'), table_name='plan_features')
    op.drop_index(op.f('ix_plan_features_feature_id'), table_name='plan_features')
    op.drop_table('plan_features')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_features_module'), table_name='features')
    op.drop_index(op.f('ix_features_code'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
