"""add hr module tables: attendance, leave, ta_da

Revision ID: 453c584202a9
Revises: deea48eb84db
Create Date: 2026-09-03 20:17:26.966129

CLAUDE.md Section 12.2/12.5 — HR module (attendance, leave, TA/DA). All
three are tenant-owned, admin-entered business data (same category as
`sales`/`stock_movements`, not a Platform-Admin-cross-tenant table like
`subscriptions`), so they get the same RLS treatment as every other
business table (Section 11.2 / migration `9196eb11b8d2`) rather than being
deferred.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '453c584202a9'
down_revision: Union[str, Sequence[str], None] = 'deea48eb84db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

RLS_TABLES = ["attendance_records", "leave_requests", "ta_da_claims"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'half_day', 'on_leave', name='attendancestatus'), nullable=False),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('check_out_at', sa.DateTime(), nullable=True),
    sa.Column('marked_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'work_date', name='uq_attendance_tenant_user_date')
    )
    op.create_index(op.f('ix_attendance_records_tenant_id'), 'attendance_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_user_id'), 'attendance_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_work_date'), 'attendance_records', ['work_date'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type', sa.Enum('casual', 'sick', 'earned', 'unpaid', name='leavetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leavestatus'), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_leave_requests_tenant_id'), 'leave_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_table('ta_da_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('travel_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_claimed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_approved', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'paid', name='tadastatus'), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_da_claims_status'), 'ta_da_claims', ['status'], unique=False)
    op.create_index(op.f('ix_ta_da_claims_tenant_id'), 'ta_da_claims', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ta_da_claims_user_id'), 'ta_da_claims', ['user_id'], unique=False)
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
            WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ta_da_claims_user_id'), table_name='ta_da_claims')
    op.drop_index(op.f('ix_ta_da_claims_tenant_id'), table_name='ta_da_claims')
    op.drop_index(op.f('ix_ta_da_claims_status'), table_name='ta_da_claims')
    op.drop_table('ta_da_claims')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_tenant_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_attendance_records_work_date'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_user_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_tenant_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
