"""add updated_at to products and barcodes

Revision ID: 9ca181e63f34
Revises: 57e25a1852ed
Create Date: 2026-08-18 21:26:37.577408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ca181e63f34'
down_revision: Union[str, Sequence[str], None] = '57e25a1852ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barcodes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_barcodes_updated_at'), 'barcodes', ['updated_at'], unique=False)
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_products_updated_at'), 'products', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_updated_at'), table_name='products')
    op.drop_column('products', 'updated_at')
    op.drop_index(op.f('ix_barcodes_updated_at'), table_name='barcodes')
    op.drop_column('barcodes', 'updated_at')
    # ### end Alembic commands ###
