"""add platform admin auth, audit log, fix override approved_by fk

Revision ID: dc90d5e6cb53
Revises: f7481532a996
Create Date: 2026-08-28 22:48:55.535201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc90d5e6cb53'
down_revision: Union[str, Sequence[str], None] = 'f7481532a996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_username'), 'platform_admins', ['username'], unique=True)
    op.create_table('platform_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_admin_id'], ['platform_admins.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_audit_log_action'), 'platform_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_created_at'), 'platform_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_platform_admin_id'), 'platform_audit_log', ['platform_admin_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_tenant_id'), 'platform_audit_log', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('tenant_feature_overrides_approved_by_fkey'), 'tenant_feature_overrides', type_='foreignkey')
    op.create_foreign_key(
        'tenant_feature_overrides_approved_by_fkey', 'tenant_feature_overrides', 'platform_admins', ['approved_by'], ['id']
    )
    op.drop_constraint(op.f('tenant_limit_overrides_approved_by_fkey'), 'tenant_limit_overrides', type_='foreignkey')
    op.create_foreign_key(
        'tenant_limit_overrides_approved_by_fkey', 'tenant_limit_overrides', 'platform_admins', ['approved_by'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_limit_overrides_approved_by_fkey', 'tenant_limit_overrides', type_='foreignkey')
    op.create_foreign_key(
        'tenant_limit_overrides_approved_by_fkey', 'tenant_limit_overrides', 'users', ['approved_by'], ['id']
    )
    op.drop_constraint('tenant_feature_overrides_approved_by_fkey', 'tenant_feature_overrides', type_='foreignkey')
    op.create_foreign_key(
        'tenant_feature_overrides_approved_by_fkey', 'tenant_feature_overrides', 'users', ['approved_by'], ['id']
    )
    op.drop_index(op.f('ix_platform_audit_log_tenant_id'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_platform_admin_id'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_created_at'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_action'), table_name='platform_audit_log')
    op.drop_table('platform_audit_log')
    op.drop_index(op.f('ix_platform_admins_username'), table_name='platform_admins')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
