"""fix upgrade_request decided_by fk to platform_admins

Revision ID: deea48eb84db
Revises: dc90d5e6cb53
Create Date: 2026-08-28 22:54:02.765728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'deea48eb84db'
down_revision: Union[str, Sequence[str], None] = 'dc90d5e6cb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('upgrade_requests_decided_by_fkey'), 'upgrade_requests', type_='foreignkey')
    op.create_foreign_key(
        'upgrade_requests_decided_by_fkey', 'upgrade_requests', 'platform_admins', ['decided_by'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('upgrade_requests_decided_by_fkey', 'upgrade_requests', type_='foreignkey')
    op.create_foreign_key(
        'upgrade_requests_decided_by_fkey', 'upgrade_requests', 'users', ['decided_by'], ['id']
    )
    # ### end Alembic commands ###
