"""add_product_extended_fields

Revision ID: fe23c5999cb1
Revises: 453c584202a9
Create Date: 2026-10-02 13:11:39.418717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe23c5999cb1'
down_revision: Union[str, Sequence[str], None] = '453c584202a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('oem_part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('warehouse', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('rack', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('bin_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('supplier_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('min_order_qty', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default='18'))
    op.add_column('products', sa.Column('safety_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('max_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('critical_part', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'critical_part')
    op.drop_column('products', 'max_stock')
    op.drop_column('products', 'safety_stock')
    op.drop_column('products', 'gst_percent')
    op.drop_column('products', 'min_order_qty')
    op.drop_column('products', 'lead_time_days')
    op.drop_column('products', 'supplier_code')
    op.drop_column('products', 'supplier_name')
    op.drop_column('products', 'bin_location')
    op.drop_column('products', 'rack')
    op.drop_column('products', 'warehouse')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'subcategory')
    op.drop_column('products', 'oem_part_number')
    # ### end Alembic commands ###
